apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-app
    repoURL: https://github.com/RJTM/argocd-playground.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
